Feature/cloud 1161 add node group
variant-inc/terraform-eksctl-nodegroup pull request #2
Opened 2022-01-11 22:05 UTC by naveen-variant

# Description

TF module for creating node groups

Fixes [#2](https://usxtech.atlassian.net/browse/CLOUD-1161)

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have used devops-playground cluster to test creation of node group.

Please use read me to test as module.
Terraform apply will create node group as per tfvars.json
Terraform destroy will delete the node group

- [ ] Sanity Testing

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added documentation to test

2022-01-12 01:17 UTC, vibindaniel commented
Naveen please add pre-commit files as done in other terraform repositories. If you don't know them, we can have a call.

2022-01-12 19:49 UTC, naveen-variant commented
> Naveen please add pre-commit files as done in other terraform repositories. If you don't know them, we can have a call.

updated as mentioned.

2022-01-12 21:07 UTC, salyateem13 commented
Please add an example in `/examples`

2022-01-12 22:21 UTC, naveen-variant commented
> Please add an example in `/examples`

Added examples to the root directory.

2022-01-14 20:22 UTC, salyateem13 commented on README.md
> +
Add requirement to export AWS_PROFILE env variable for eksctl provider

2022-01-14 20:23 UTC, salyateem13 commented on outputs.tf
> +output "kubeconfig_path" {
Why is this output called kubeconfig_path

2022-01-14 21:00 UTC, naveen-variant commented on README.md
> +
Added.

2022-01-14 21:00 UTC, naveen-variant commented on outputs.tf
> +output "kubeconfig_path" {
Updated the name

2022-01-14 23:36 UTC, salyateem13 approved these changes

2022-01-17 16:27 UTC, vibindaniel commented on versions.tf
> +      version = "0.16.2"
>=0.16.2

2022-01-17 16:28 UTC, vibindaniel commented on main.tf
> +resource "eksctl_nodegroup" "ng" {
Where are the labels?

2022-01-17 16:28 UTC, vibindaniel commented on main.tf
> +resource "eksctl_nodegroup" "ng" {
Without labels autoscaling won't work

2022-01-17 16:30 UTC, vibindaniel requested changes
@naveen-variant Please go through the eksctl template used in iaac-eks and add all the fields mentioned there. I see 

disableIMDSv1
labels
taints

not added


disableIMDSv1 - Default is false, updating it to true will not allow us to set other iam parameters.
labels - Added
taints- There seems to be no support to add taints from eksctl nodegroup command. Tried checking in  eksctl create nodegroup -h command.

2022-01-17 17:21 UTC, naveen-variant commented on versions.tf
> +      version = "0.16.2"
version parameter is not supporting decimal values. Have to be a string literal.

2022-01-17 17:21 UTC, naveen-variant commented on main.tf
> +resource "eksctl_nodegroup" "ng" {
Added labels parameter

2022-01-17 20:12 UTC, vibindaniel commented on versions.tf
> +      version = "0.16.2"
`>=0.16.2

2022-01-19 17:49 UTC, salyateem13 approved these changes

2022-01-19 17:54 UTC, merged